source 'http://rubygems.org'

gem 'rails', '4.2.1'
gem 'delayed_job_active_record'
gem 'json'
gem 'jquery-rails'
gem 'rspec'
gem 'rspec-rails'
gem 'capistrano'
gem 'capistrano-ext'
gem 'pg'
gem 'haml'
gem 'insales_api', github: "insales/insales_api", branch: "master"
gem 'sqlite3'
gem 'actionpack-xml_parser'
gem 'pry-byebug'
